Handle versioning

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -39,12 +39,13 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        python-version: ["3.9", "3.13", "3.14"]
+        python-version: ["3.9", "3.13", "3.14", "3.14t"]
     steps:
     - name: Check out code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
+        fetch-tags: true
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
@@ -55,6 +56,22 @@ jobs:
       with:
         enable-cache: true
         python-version: ${{ matrix.python-version }}
+    - uses: mtkennerly/dunamai-action@v1
+      with:
+        env-var: PROJECT_VERSION
+        args: --style semver
+    - name: Update __version__ and pyproject.toml
+      run: |
+        if [[ "$PROJECT_VERSION" == 0.0.0* ]]; then
+          echo "Invalid version: $PROJECT_VERSION"
+          exit 1
+        fi
+        echo "__version__ = '${PROJECT_VERSION}'" > pyrate_limiter/_version.py
+        uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $PROJECT_VERSION
+        echo _version.py is:
+        cat pyrate_limiter/_version.py
+        echo pyproject.toml version is
+        grep version pyproject.toml
     - name: Install dependencies
       run: uv sync --all-groups --all-extras
     # Run linting (latest python version only)
@@ -62,22 +79,8 @@ jobs:
       if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
       run: |
         uv run nox -e lint
-    - uses: mtkennerly/dunamai-action@v1
-      with:
-        env-var: PROJECT_VERSION
-        args: --style semver
-    - name: Fail if version is 0.0.0
-      run: |
-        if [ "$PROJECT_VERSION" = "0.0.0" ]; then
-          echo "Invalid version: $PROJECT_VERSION"
-          exit 1
-        fi
     - name: Build and install package, if this is latest
       run: |
-        # update version
-        echo "__version__ = '$(PROJECT_VERSION)'" > pyrate_limiter/_version.py
-        uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $PROJECT_VERSION
-        echo version = $version
         uv build
         uv pip install dist/*.whl
     # Run tests and coverage report (all python versions)
