simplify - use uv_build backend

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -39,7 +39,7 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        python-version: ["3.9", "3.13"]
+        python-version: ["3.9", "3.13", "3.14"]
     steps:
     - name: Check out code
       uses: actions/checkout@v4
@@ -62,8 +62,22 @@ jobs:
       if: ${{ matrix.python-version == env.LATEST_PY_VERSION }}
       run: |
         uv run nox -e lint
+    - uses: mtkennerly/dunamai-action@v1
+      with:
+        env-var: PROJECT_VERSION
+        args: --style semver
+    - name: Fail if version is 0.0.0
+      run: |
+        if [ "$PROJECT_VERSION" = "0.0.0" ]; then
+          echo "Invalid version: $PROJECT_VERSION"
+          exit 1
+        fi
     - name: Build and install package, if this is latest
       run: |
+        # update version
+        echo "__version__ = '$(PROJECT_VERSION)'" > pyrate_limiter/_version.py
+        uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $PROJECT_VERSION
+        echo version = $version
         uv build
         uv pip install dist/*.whl
     # Run tests and coverage report (all python versions)
